### PR TITLE
using the real exploration services now that they are available

### PR DESCRIPTION
**Pull request by bfalacerda**

### CODE REVIEW

**Comment by santosj** [comment]
@bfalacerda I accepted a previous request and I it seems there are some conflicts. Can you have a look at it? Sorry about this.

**Comment by bfalacerda** [comment]
I just added lots of commits by @ferdianjovan by mistake. Are these to be merged @ferdianjovan , or shall I create a new PR without your stuff?

**Comment by ferdianjovan** [comment]
My stuff has been merged by @santosj.
So, probably would be better if you leave my stuff out first.

**Comment by bfalacerda** [comment]
closing this to make a clean PR

**Pull request closed without merging**
