### PR TITLE
Activity Exploration with Bidding Policy

### PR DESCRIPTION
**Pull request by ferdianjovan**
Many codes are removed from activity_exploration.
Now, to run activity_exploration you need https://github.com/ferdianjovan/spatio_temporal_activity_patterns.git

Codes are not tested yet.

### CODE REVIEW

**Comment by ferdianjovan** [comment]
There is a launch file where you can run by
`roslaunch activity_exploration activity_exploration.launch soma_config:=[soma_configuration]`
also you need to run
`roslaunch people_temporal_patterns peetrap.launch soma_config:=[soma_configuration]`
from https://github.com/ferdianjovan/spatio_temporal_activity_patterns.git

**Comment by heuristicus** [comment]
Got this error while running.

``` sh
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/timer.py", line 223, in run
    self._callback(TimerEvent(last_expected, last_real, current_expected, current_real, last_duration))
  File "/home/strands/tsc_y4_ws/src/strands_exploration/activity_exploration/src/activity_exploration/exploration.py", line 98, in request_exploration
    budget = self.budget_control.get_allocated_budget(start_time, end_time)
  File "/home/strands/tsc_y4_ws/src/strands_exploration/activity_exploration/src/activity_exploration/budget_control.py", line 107, in get_allocated_budget
    people_estimates = self._people_srv(start_time, end_budget_time, True, False)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 512, in call
    transport.send_message(request, self.seq)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 634, in send_message
    serialize_message(self.write_buff, seq, msg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/home/strands/tsc_y4_ws/devel/lib/python2.7/dist-packages/people_temporal_patterns/srv/_PeopleEstimateSrv.py", line 67, in serialize
    buff.write(_struct_4I2B.pack(_x.start_time.secs, _x.start_time.nsecs, _x.end_time.secs, _x.end_time.nsecs, _x.upper_bound, _x.scale))
AttributeError: 'datetime.time' object has no attribute 'secs'
```

**Comment by ferdianjovan** [comment]
Yeay, error. Will try to look at that and fix it.
Thanks @heuristicus

**Comment by heuristicus** [comment]
Another one for you:

``` sh
Exception in thread Thread-10:                                                                                                                                                                                                         
Traceback (most recent call last):                                                                                                                                                                                                     File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner                                                                                                                                                               self.run()
File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/timer.py", line 223, in run                                                                                                                                                  
    self._callback(TimerEvent(last_expected, last_real, current_expected, current_real, last_duration))
File "/home/strands/tsc_y4_ws/src/strands_exploration/activity_exploration/src/activity_exploration/exploration.py", line 125, in request_exploration                                                                                
    idx = random.randint(2)                                                                                                                                                                                                          
TypeError: randint() takes exactly 3 arguments (2 given)
```

**Pull request merged**
