### PR TITLE
Activity Exploration

### PR DESCRIPTION
**Pull request by ferdianjovan**
There are some changes related to edge_exploration/scripts/exploration_slots.py
@bfalacerda @Jailander should I open a new PR?

### CODE REVIEW

**Comment by Jailander** [comment]
Hi if @bfalacerda agrees its better to merge https://github.com/strands-project/strands_exploration/pull/15 close this one and then open a new one with your changes only

**Comment by bfalacerda** [comment]
yep

**Comment by ferdianjovan** [comment]
Ok

**Comment by Jailander** [comment]
ok @ferdianjovan #15 is merged now open a new PR with your stuff

**Pull request closed without merging**
