### PR TITLE
[Edge exploration]

### PR DESCRIPTION
**Pull request by Jailander**
now it will only explore edges with high success probability

### CODE REVIEW

**Comment by bfalacerda** [comment]
does this also take into account the number of samples we have for the edge? I think we should only start avoiding them when we have enough data to be sure it's a bad edge

**Comment by Jailander** [comment]
yes it does, but only when there are no samples after one sample it depends on the probability you are right I'll fix this/

**Comment by Jailander** [comment]
@bfalacerda now its fixed

**Comment by bfalacerda** [comment]
great, thanks. I'll put it in betty

**Pull request merged**
