### PR TITLE
using the real exploration services now that they are available

### PR DESCRIPTION
**Pull request by bfalacerda**
@santosj @ferdianjovan please make sure that I didn't  mess anything in your code while cherry picking.

### CODE REVIEW

**Comment by santosj** [comment]
it looks ok for me

**Comment by ferdianjovan** [comment]
There is a change on activity_exploration/src/region_observation/observe.py
Do you intend to change that @bfalacerda ?

**Comment by bfalacerda** [comment]
@ferdianjovan yes, sometimes we had problems when starting the node before, if the callback for pose was called before the one for ptu

**Comment by ferdianjovan** [comment]
is it because self._pan_orientation? I thought I set init self._pan_orientation with 0.0.
ah ok if that is the case, I am ok with that.

**Pull request merged**
