### PR TITLE
learn objects while doing fremen grid exploration at office hours

### PR DESCRIPTION
**Pull request by bfalacerda**
please test to see if the `learn_object` tasks are being defined correctly

### CODE REVIEW

**Comment by hawesie** [comment]
@bfalacerda should I worry about the failed checks?

**Comment by bfalacerda** [comment]
i also added some parameter server stuff so we can tweak the exploration behaviour while it is running

**Comment by hawesie** [comment]
A learn task was created. Is this always happening, or is it just for some percentage?

**Comment by bfalacerda** [comment]
at office hours, always

**Comment by hawesie** [comment]
Could it be probabilistic? Perhaps related to the score? I don't think we always want them to be learning actions.

**Comment by bfalacerda** [comment]
it can. however, if there are no changes it will just do the metaroom right? During office hours shouldn't we try to learn as much objects as possible?

**Comment by hawesie** [comment]
it's just a bit intrusive to be doing it all the time right around desks where people are working doing 1 in 4 or something would be enough

**Comment by bfalacerda** [comment]
ok

**Comment by bfalacerda** [comment]
did the reduction on object learns; also edited the management of activity tracking

**Pull request merged**
